name: Continuous testing and publication to NPM from 'master'

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflows }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:

  run-js-tests:
    runs-on: ubuntu-latest
    if: github.repository != 'Exabyte-io/template-definitions'
    strategy:
      matrix:
        node-version: [8.x]

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Checkout actions repository
        uses: actions/checkout@v2
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions

#      - name: Run JS tests
#        uses: ./actions/js/test
#        with:
#          node-version: ${{ matrix.node-version }}

  publish-js-package:
    needs: [run-js-tests]
    runs-on: ubuntu-latest
    if: (github.repository != 'Exabyte-io/template-definitions') && (github.ref_name == 'master')

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Checkout actions repository
        uses: actions/checkout@v2
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions

      - name: Publish JS release
        uses: ./actions/js/publish
        with:
          node-version: 8.11.4
          verify-tests: false
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}

